[package]
name = "kernel-logging"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
spin.workspace = true
kernel-hw-io-serial.workspace = true
kernel-hw-io.workspace = true

