[package]
name = "kernel-io-serial"
version.workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"
edition = "2021"

[dependencies]
kernel-io-defs.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true
