[package]
name = "kernel-hw-io-serial"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]
kernel-hw-io.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true
