[package]
name = "kernel-hw-cpu"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]
path = "lib.rs"

[dependencies]

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64.workspace = true

